### ISSUE TITLE
If a payment is not completed immediatley, then outlay will not be updated

### ISSUE THREAD

**Issue by gudnuf** [gudnuf/bolt12-prism#47] opened 2023-07-02 05:13 UTC
This may require us to subscribe to outgoing payments then check its paying any outstanding funds

**Comment by daGoodenough** [comment] 2023-07-02 20:37
It seems there is also a bug and outlays are not being correctly updated

**Comment by farscapian** [comment] 2024-06-07 22:51
I think this issue is closed in the latest release. This behavior us by design. Outlays all get updated first. Then outlays only go down upon successful payout.

**Closed by farscapian** 2024-06-07 22:51 UTC
Labels: bug
